name: docs

on:
  pull_request:
    branches:
      - main

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version-file: 'go.mod'
      - name: gomarkdoc
        id: gomarkdoc
        run: |
          go install github.com/princjef/gomarkdoc/cmd/gomarkdoc@latest
          make generate/gomarkdoc
      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          message: 'Update documentation'
          author_name: GitHub Actions
          author_email: 41898282+github-actions[bot]@users.noreply.github.com
